### PR TITLE
Update to Spree 2.4-stable

### PR DESCRIPTION
**Pull request by bryanmtl**
This PR will update the extension to work with Spree 2.4-stable.

### CODE REVIEW

**Comment by mickeyren** [comment]
hi @bryanmtl 

just a progress update, I've added a bunch of specs for the subscription model's new methods the - https://github.com/DynamoMTL/spree_subscriptions/compare/708cb404344d061ee7dc6d74c9517a9c1a7a3cba...86a9aab0b645802e6467f8555ba60d1e80f7a70d

all tests passing, i'll see if it makes sense to add more specs to the other parts.

**Comment by mickeyren** [comment]
Hi @bryanmtl 

I've written more specs - covering the subscription api controller - https://github.com/DynamoMTL/spree_subscriptions/compare/708cb404344d061ee7dc6d74c9517a9c1a7a3cba...927ca8e39e722a5656d8e0145077a86a6151c587

```Finished in 1 minute 10.18 seconds (files took 4.13 seconds to load)
57 examples, 0 failures, 1 pending```

do you think this deserve to be merge now? I know there's still specs to write, but i wanted to start alternating wiring the subscription for Glossier.

**Comment by bryanmtl** [comment]
Sounds good to me. Thanks for adding those. 



-- 
 
BRYAN MAHONEY
bryan@godynamo.com
http://twitter.com/#!/bryanmtl
 DYNAMO
http://www.goDynamo.com
http://twitter.com/dynamomtl
http://facebook.com/dynamomtl
 
TEL 514 499 2843 x21 | CEL 514 804 2843
439 Rue St-Pierre, Vieux-Montréal, Québec H2Y2M8 CANADA

**Comment by mickeyren** [comment]
thanks @bryanmtl it's now fully merged to 2-4-stable.

do you want 2-4-stable merge to master as well?

**Comment by bryanmtl** [comment]
Yup. Go for it. 



-- 
 
BRYAN MAHONEY
bryan@godynamo.com
http://twitter.com/#!/bryanmtl
 DYNAMO
http://www.goDynamo.com
http://twitter.com/dynamomtl
http://facebook.com/dynamomtl
 
TEL 514 499 2843 x21 | CEL 514 804 2843
439 Rue St-Pierre, Vieux-Montréal, Québec H2Y2M8 CANADA

**Pull request closed without merging**
